#
#Sat Sep 05 12:17:57 GMT+04:00 2026
db-address=. ds.db
db-driver=org.sqlite.JDBC
db-name=
db-password=
db-port=
db-type=sqlite
db-user=
db-using-type=update
log-app=false
use-dark=true
use-laf=true
